name: ngs-variants
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools=1.20
  - bcftools=1.20
  - htslib=1.20
  - freebayes=1.3.7
  - bwa=0.7.18
  - wgsim
  - seqkit=2.8.2
  - python=3.12
  - wget
  - curl
