name: ngs-interpret
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - ensembl-vep=110.0
  - bcftools=1.20
  - samtools=1.20
  - htslib=1.20
  - tabix
  - wget
  - curl
  - jq
  - matplotlib=3.9
  - pandas=2.2
  - seqkit=2.8.2
